platform :ios, '11.0'

target 'PhotosApp' do
  use_frameworks!

  # Pods for PhotosApp
  # UI pods
  pod 'Kingfisher'

  target 'PhotosAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
